<div class="onestepcheckout-login onestepcheckout-formpopup" id="onestepcheckout-login">
	<div class="page-title">
    <h3 style="float:left;"><?php echo $this->__('Login'); ?></h3>
		<div class="close-box right">
			<p class="right"><a href="" onclick="javascript:TINY.box.hide();return false">Sluiten</a></p>
		</div>
	</div>	
<div id="wrapper_login">
	<div style="float:left;width:100%;">
		<div class="step-subtitle left"><?php echo $this->__('Hieronder kunt u inloggen met uw gebruikersnaam en wachtwoord.');?></div>	
	</div>	
	<div id="onestepcheckout-login-loading" style="display: none;" class="loading-ajax">&nbsp;</div>
	<div id="onestepcheckout-login-error-message" style="display:none;"></div>
	<form action="<?php echo $this->getUrl('customer/account/loginPost');?>" method="post" id="onestepcheckout-login-form">
		<div class="login-fields">
			<ul>
				<li>
					<div class="input-field">
						<label><?php echo $this->__('Emailadres');?><span class="required">*</span></label>
						<div class="clear"></div>
						<input type="text" name="osclogin[email_address]" id="osclogin:email_address" class="input-text required-entry validate-email" value=""/>
					</div>
				</li>
				<li>
					<div class="input-field">
						<label><?php echo $this->__('Wachtwoord');?><span class="required">*</span></label>
						<div class="clear"></div>
						<input type="password" name="osclogin[password]" id="osclogin:password" class="input-text required-entry validate-password" value=""/>
					</div>
				</li>
			</ul>
		</div>
		<div class="login-button">
			<p class="left"><a href="" onclick="showPasswordForm();return false;">Wachtwoord vergeten?</a></p>
			<p class="right">
				<button type="button" class="button" title="<?php echo $this->__('Login') ?>" name="button-login" id="osc-button-login" onclick="submitLoginForm(); return false;"><?php echo $this->__('Login') ?></button>
			</p>	
		</div>
	</form>
</div>
</div>

<!-- Forgot password field-->
<div class="onestepcheckout-forgot-password onestepcheckout-formpopup" id="onestepcheckout-forgot-password" style="display:none;">
	<div class="page-title">
		<h3 style="float:left;"><?php echo $this->__('Uw wachtwoord vergeten?') ?></h3>
		<div class="close-box right">
			<p class="right"><a href="" onclick="javascript:TINY.box.hide();return false">Sluiten</a></p>
		</div>
	</div>
<div id="wrapper_login">
	<div style="float:left;width:100%;">

		<div class="clear"></div>
		<div class="step-subtitle left"><?php echo $this->__("Vul uw emailadres hieronder in en wij sturen u een nieuw wachtwoord.");?></div>
	<div id="onestepcheckout-password-loading" style="display: none;" class="loading-ajax">&nbsp;</div>
	<div id="onestepcheckout-password-error-message" style="display:none;"></div>
	<div id="onestepcheckout-password-success-message" style="display:none;">Een nieuw wachtwoord is naar uw Emailadres verstuurd. Klik op de onderstaande link om terug te keren naar de login pagina.</div>
	<form action="" method="post" id="osc-forgotpassword-form">
		<div class="login-fields">
			<ul>
				<li>
					<div class="input-text">
						<label><?php echo $this->__('Emailadres');?><span class="required">*</span></label>
						<div class="clear"></div>
						<input type="text" name="email" alt="email" id="forgotpassword_email_address" class="input-text required-entry validate-email" value="<?php echo $this->htmlEscape($this->getEmailValue()) ?>" />
					</div>
				</li>
			</ul>
		</div>
		<div class="login-button">
			<p class="back-link left"><a href="" onclick="showloginform();return false;"><small>&laquo; </small><?php echo $this->__('Terug naar Login') ?></a></p>
			<p class="right"><button type="button" class="button" title="<?php echo $this->__('Verzenden') ?>" onclick="retrievePassword(); return false;"><?php echo $this->__('Verzenden') ?></button></p>
		</div>
	</form>
</div>
</div>