<div class="gift-messages">	
	<input type="checkbox" name="allow_gift_messages" id="allow_gift_messages" value="1" <?php if($this->getItemsHasMesssages() || $this->getEntityHasMessage()): ?> checked="checked"<?php endif; ?> class="checkbox" />
	<label for="allow_gift_messages"><?php echo $this->__('Check this checkbox if you want to add gift messages.') ?></label>	
</div>
<div class="gift-messages-form" id="allow-gift-message-container">
	<div class="inner-box">
		<?php if (Mage::helper('onestepcheckout/message')->isMessagesAvailable('quote', $this->getEntity())): ?>
			<div class="whole-order">
				<h4><?php echo $this->__('Enter a gift message for entire order.'); ?></h4>
				<p><?php echo $this->__('You can leave this box blank if you do not wish to add a gift message for whole order.') ?></p>
				<input type="hidden" name="giftmessage[<?php echo $this->getEntity()->getId() ?>][type]"  value="quote" />
				<ul class="onestepcheckout-form-list">
					<li class="fields">
						<div class="field">
							<label for="gift-message-whole-from"><?php echo $this->__('From') ?></label>
							<div class="input-box">
								<input type="text" name="giftmessage[<?php echo $this->getEntity()->getId() ?>][from]" id="gift-message-whole-from" title="<?php echo $this->__('From') ?>"  value="<?php echo $this->getEscaped($this->getMessage()->getSender(), $this->getDefaultFrom()) ?>" class="input-text validation-passed" />
							</div>
						</div>
						<div class="field f-right">
							<label for="gift-message-whole-to"><?php echo $this->__('To') ?></label>
							<div class="input-box">
								<input type="text" name="giftmessage[<?php echo $this->getEntity()->getId() ?>][to]" id="gift-message-whole-to" title="<?php echo $this->__('To') ?>" value="<?php echo $this->getEscaped($this->getMessage()->getRecipient(), $this->getDefaultTo()) ?>" class="input-text validation-passed" />
							</div>
						</div>
					</li>
					<li class="wide">
						<label for="gift-message-whole-message"><?php echo $this->__('Message') ?></label>
						<div class="input-box">
							<textarea id="gift-message-whole-message" class="input-text validation-passed giftmessage-area" name="giftmessage[<?php echo $this->getEntity()->getId() ?>][message]" title="<?php echo $this->__('Message') ?>" rows="5" cols="10"><?php echo $this->getEscaped($this->getMessage()->getMessage()) ?></textarea>
						</div>
					</li>
				</ul>
				<script type="text/javascript">
				//<![CDATA[
					//toogleRequired('gift-message-whole-message', ['gift-message-whole-from','gift-message-whole-to']);
				//]]>
				</script>
			</div>
		<?php endif; ?>	
	</div>
</div>
<script type="text/javascript">
//<![CDATA[
	Event.observe(window, 'load', function() {
		if ($('allow_gift_messages').checked) {
			$('allow-gift-message-container').show();
		}
		else {
			$('allow-gift-message-container').hide();
		}
		
		Event.observe('allow_gift_messages', 'click', function() {
			if ($('allow_gift_messages').checked) {
				$('allow-gift-message-container').show();
			}
			else {
				$('allow-gift-message-container').hide();
			}
		});
	});
//]]>
</script>