<div>
    <p>
        <?php $_product_ids=$this->getFeaturedProduct() ?>
    </p>
    <?php //print_r($_product);?>
    <?php // Product Image
foreach($_product_ids as $_product_id) {
    $_product = Mage::getModel('catalog/product')->setStoreId($storeId)->load($_product_id);
 
?>
    <div style="float: left;"> <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->htmlEscape($this->getImageLabel($_product, 'small_image')) ?>" class="product-image"><img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(135); ?>" width="135" height="135" alt="<?php echo $this->htmlEscape($this->getImageLabel($_product, 'small_image')) ?>" /></a>&nbsp;&nbsp; </div>
    <div style="float: left;">
        <p> <a href="<?php echo $_product->getProductUrl() ?>"><?php echo $this->htmlEscape($_product->getName()) ?></a></p>
        <p><?php echo $this->htmlEscape($_product->getShortDescription()) ?></p>
    </div>
    <?php } ?>
</div>