<div class="block right-nav">
    <div class="block-title">
        <h3><?php echo $this->__('Categorie navigatie') ?></h3>
    </div>
    <div class="block-content">
        <ul id="right-nav">
         
		<?php
		$obj = new Mage_Catalog_Block_Navigation();
		$store_cats    = $obj->getStoreCategories();
		$current_cat     = $obj->getCurrentCategory();
		$current_cat    = (is_object($current_cat) ? $current_cat->getName() : '');
 
		foreach ($store_cats as $cat) {
			if ($cat->getName() == $current_cat) {
				echo '<li class="category active"><a href="'.$this->getCategoryUrl($cat).'">'.$cat->getName()."</a>\n<ul class='subcategory'>\n";
				foreach ($obj->getCurrentChildCategories() as $subcat) {
					echo '<li><a href="'.$this->getCategoryUrl($subcat).'">'.$subcat->getName()."</a></li>\n";
				}
				echo "</ul>\n</li>\n";
			} else {
				echo '<li class="category"><a href="'.$this->getCategoryUrl($cat).'">'.$cat->getName()."</a></li>\n";
			}
		}
		?> 
		 
        </ul>
    </div>
</div>
 